@baseUrl = http://localhost:3000/api
### GET all shifts
GET {{baseUrl}}/shifts

### GET shift by id
GET {{baseUrl}}/shifts/1773058654133

### POST shift
POST {{baseUrl}}/shifts
Content-Type: application/json

{
  "username": "Vova",
  "date": "2026-05-02",
  "time": "day",
  "status": "missed",
  "comment": "asdasd"
}

### PUT shift
PUT {{baseUrl}}/shifts/e409299e-8501-4be4-b4fa-8b06ab0fa25e
Content-Type: application/json

{
  "username": "Marlboro",
  "date": "2026-04-20",
  "time": "evening",
  "status": "missed",
  "comment": "fff"
}

### DELETE shift
DELETE {{baseUrl}}/shifts/1773058654133