@baseUrl = http://localhost:3000/api
### GET all shifts
GET {{baseUrl}}/shifts?sortBy=date&status=scheduled&userId=d16f0fc1-90bd-482a-9c87-03da6a0ff6ef

### GET shift by id
GET {{baseUrl}}/shifts/85f6a9a3-dcc5-42d0-86cc-4dea61088d1d

### POST shift
POST {{baseUrl}}/shifts
Content-Type: application/json

{
  "username": "Ihor",
  "date": "2025-06-24",
  "time": "evening",
  "status": "completed"
}

### PUT shift
PUT {{baseUrl}}/shifts/85f6a9a3-dcc5-42d0-86cc-4dea61088d1d
Content-Type: application/json

{
  "status": "completed",
  "comment": "fff"
}

### DELETE shift
DELETE {{baseUrl}}/shifts/85f6a9a3-dcc5-42d0-86cc-4dea61088d1d

### Stats on shifts
GET {{baseUrl}}/shifts/stats