@baseUrl = http://localhost:3000/api
### GET all users
GET {{baseUrl}}/users?sortBy=username&sortDir=asc

### GET user by id
GET {{baseUrl}}/users/e971b1a1-845a-42b9-8b33-60e24fb2f529

### POST user
POST {{baseUrl}}/users/
Content-Type: application/json

{
  "username": "ae220k"
}

### PUT user
PUT {{baseUrl}}/users/e971b1a1-845a-42b9-8b33-60e24fb2f529
Content-Type: application/json

{
  "username": "Alex"
}

### DELETE user
DELETE {{baseUrl}}/users/e971b1a1-845a-42b9-8b33-60e24fb2f529