@baseUrl = http://localhost:3000/api
### GET all users
GET {{baseUrl}}/users

### GET user by id
GET {{baseUrl}}/users/123

### POST user
POST {{baseUrl}}/users/
Content-Type: application/json

{
  "username": "3"
}

### PUT user
PUT {{baseUrl}}/users/8d485c4c-3e69-4438-9f2f-a1f3dbb42ead
Content-Type: application/json

{
  "username": "Alex"
}

### DELETE user
DELETE {{baseUrl}}/users/8d485c4c-3e69-4438-9f2f-a1f3dbb42ead